# -*- coding: utf-8 -*-
"""Copy of trial_1_week_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muB8GAZpxfWNtXfMEfADgUhOvGu1GbC2

Install Dependencies
"""

!pip install -q yt-dlp openai-whisper
!apt-get -qq install ffmpeg

!ffmpeg -version

"""Download Video"""

# import yt_dlp

# url = "https://www.youtube.com/watch?v=_f7xDWZzn4c"

# ydl_opts = {
#     "format": "bestvideo+bestaudio/best",
#     "merge_output_format": "mp4",
#     "outtmpl": "video.%(ext)s",
#     "quiet": False,
#  }
# with yt_dlp.YoutubeDL(ydl_opts) as ydl:
#     ydl.download([url])

"""Extract Audio"""

# Use FFmpeg to extract audio from the downloaded video file
!ffmpeg -i /content/video.mp4 \
    -ar 16000 \
    -ac 1 \
    /content/audio.wav \
    -y

"""Load Whisper ( to convert audio to text )"""

import whisper

model = whisper.load_model("base")

import torch
print(torch.cuda.is_available())

"""Generate Transcript"""

# Transcribe the audio file using the loaded Whisper model
result = model.transcribe(
    "/content/audio.wav",
    word_timestamps=True               # create timestamps
)

# Loop through the first 10 transcription segments
for seg in result["segments"][:10]:
    print(
        f"[{seg['start']:.2f} - {seg['end']:.2f}]",
        seg['text']
    )

"""Save as JSON FILE"""

# Save the transcript data in JSON format
import json

transcript2 = []

for seg in result["segments"]:
    transcript2.append({
        "start": seg["start"],
        "end": seg["end"],
        "text": seg["text"]
    })

with open("/content/transcript2.json", "w") as f:
    json.dump(transcript2, f, indent=4)

"""Download JSON FILE"""

from google.colab import files

files.download('/content/transcript2.json')

!pip install contractions

import json

file_path = "/content/transcript2.json"

with open(file_path, "r", encoding="utf-8") as f:
    transcript = json.load(f)

print("Transcript loaded successfully!")
print("Number of segments:", len(transcript))

import json
import re
import contractions

FILLERS = [
    "um", "uh", "erm", "ah", "hmm",
    "you know", "like", "sort of", "kind of"
]

def clean_text(text):

    # Expand contractions
    text = contractions.fix(text)

    # Convert to lowercase
    text = text.lower()

    # Remove filler words
    for filler in FILLERS:
        pattern = r"\b" + re.escape(filler) + r"\b"
        text = re.sub(pattern, "", text)

    # Remove unwanted punctuation
    text = re.sub(r"[^\w\s?.!]", "", text)

    # Normalize repeated punctuation
    text = re.sub(r"\?+", "?", text)
    text = re.sub(r"!+", "!", text)
    text = re.sub(r"\.+", ".", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

cleaned_segments = []

for segment in transcript:

    cleaned_segments.append({
        "start": segment["start"],
        "end": segment["end"],
        "text": clean_text(segment["text"])
    })

print("Cleaning done:", len(cleaned_segments))

# Save cleaned transcript
with open("cleaned_transcript.json", "w", encoding="utf-8") as f:
    json.dump({"segments": cleaned_segments}, f, indent=4)

print("Transcript cleaned successfully!")

from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print(type(cleaned_segments))
print(type(cleaned_segments[0]))

print(any(len(s.get("text", "").strip()) == 0 for s in cleaned_segments))

labels = [
    "Question",
    "Answer",
    "Agreement",
    "Disagreement",
    "Neutral"
]

# Remove empty text segments
valid_segments = [
    seg for seg in cleaned_segments
    if seg.get("text") and seg["text"].strip()
]

print("Original segments:", len(cleaned_segments))
print("Valid segments:", len(valid_segments))

texts = [
    s["text"].strip()
    for s in cleaned_segments
    if s.get("text", "").strip()
]

results

events = []

for i, seg in enumerate(valid_segments):

    result = classifier(
        seg["text"],
        candidate_labels=labels
    )

    label = result["labels"][0]
    confidence = float(result["scores"][0])

    events.append({
        "start": seg["start"],
        "end": seg["end"],
        "text": seg["text"],
        "label": label,
        "confidence": round(confidence, 3)
    })

    if i % 50 == 0:
        print(f"Processed {i}/{len(valid_segments)}")

import json

with open("classified_segments.json", "w", encoding="utf-8") as f:
    json.dump(events, f, indent=4)

print("Classification completed!")

import json

with open("classified_segments.json", "r", encoding="utf-8") as f:
    classified_segments = json.load(f)

print(len(classified_segments))
print(classified_segments[0])

import json

detected_events = []

# Minimum confidence required
CONFIDENCE_THRESHOLD = 0.45


for i, seg in enumerate(classified_segments):

    label = seg["label"]
    confidence = seg["confidence"]


    # Ignore weak predictions
    if confidence < CONFIDENCE_THRESHOLD:
        continue


    # --------------------------------
    # Question-Answer Detection
    # --------------------------------

    if label == "Question":

        answer = None

        # Search next 3 segments for Answer
        for j in range(
            i + 1,
            min(i + 4, len(classified_segments))
        ):

            next_seg = classified_segments[j]

            if (
                next_seg["label"] == "Answer"
                and
                next_seg["confidence"] >= CONFIDENCE_THRESHOLD
            ):

                answer = next_seg
                break


        if answer:

            detected_events.append({

                "event": "Question-Answer",

                "start": seg["start"],

                "end": answer["end"],

                "question": seg["text"],

                "answer": answer["text"],

                "confidence": round(
                    (
                        seg["confidence"]
                        +
                        answer["confidence"]
                    ) / 2,
                    3
                )

            })


    # --------------------------------
    # Agreement Detection
    # --------------------------------

    elif label == "Agreement":

        detected_events.append({

            "event": "Agreement",

            "start": seg["start"],

            "end": seg["end"],

            "text": seg["text"],

            "confidence": confidence

        })


    # --------------------------------
    # Disagreement Detection
    # --------------------------------

    elif label == "Disagreement":

        detected_events.append({

            "event": "Disagreement",

            "start": seg["start"],

            "end": seg["end"],

            "text": seg["text"],

            "confidence": confidence

        })


print("Detected events:", len(detected_events))

with open("detected_events.json", "w", encoding="utf-8") as f:
    json.dump(detected_events, f, indent=4)

print("Event detection completed!")

import os

print(os.listdir())

!pip uninstall moviepy -y
!pip install moviepy==1.0.3

import json
from moviepy.editor import VideoFileClip, concatenate_videoclips


VIDEO_PATH = "video.mp4"
EVENTS_PATH = "detected_events.json"

BUFFER_BEFORE = 5
BUFFER_AFTER = 5

MAX_CLIP_DURATION = 10
TARGET_DURATION = 60


# -----------------------------
# Load video
# -----------------------------

video = VideoFileClip(VIDEO_PATH)

video_duration = video.duration


# -----------------------------
# Load detected events
# -----------------------------

with open(EVENTS_PATH, "r", encoding="utf-8") as f:
    events = json.load(f)


# Sort by confidence
events = sorted(
    events,
    key=lambda x: x["confidence"],
    reverse=True
)


selected_clips = []
selected_events = []

total_duration = 0


# -----------------------------
# Select multiple important clips
# -----------------------------

for event in events:

    if total_duration >= TARGET_DURATION:
        break


    start = max(
        0,
        event["start"] - BUFFER_BEFORE
    )

    end = min(
        video_duration,
        event["end"] + BUFFER_AFTER
    )


    duration = end - start


    # Limit individual clips
    if duration > MAX_CLIP_DURATION:
        end = start + MAX_CLIP_DURATION
        duration = MAX_CLIP_DURATION


    # Avoid duplicate clips
    overlap = False

    for selected in selected_events:

        if abs(start - selected["start"]) < 15:
            overlap = True
            break


    if overlap:
        continue


    selected_events.append({
        "start": start,
        "end": end,
        "event": event["event"]
    })


    clip = video.subclip(
        start,
        end
    )

    selected_clips.append(clip)

    total_duration += duration



print("Number of clips:", len(selected_clips))
print("Total duration:", total_duration)



# -----------------------------
# Combine clips
# -----------------------------

if selected_clips:

    final_video = concatenate_videoclips(
        selected_clips,
        method="compose"
    )


    # Trim final output exactly to 60 sec
    if final_video.duration > TARGET_DURATION:
        final_video = final_video.subclip(
            0,
            TARGET_DURATION
        )


    final_video.write_videofile(
        "highlight_video.mp4",
        codec="libx264",
        audio_codec="aac"
    )


    print("1 minute highlight video created!")

else:
    print("No clips selected")

from IPython.display import Video, display

video_path = "highlight_video.mp4"

display(
    Video(
        video_path,
        embed=True,
        width=700
    )
)

